export function downloadFile(name: string) {
  const content = `This is a dummy file for: ${name}\nGenerated by Client Portal 🚀`;

  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = name;
  link.click();

  URL.revokeObjectURL(url);
}
